/**
 * Fix missing AdvJS statements based on a report file
 * 
 * Usage: node Bob/fix_advjs_from_report.js <report_file.txt>
 * Example: node Bob/fix_advjs_from_report.js Bob/bob_output/missing_advjs_imports_b_files.txt
 * 
 * This script:
 * 1. Reads the report file generated by check_missing_advjs_imports.js
 * 2. Extracts the list of files missing statements
 * 3. Adds the required import statements to those files
 */

const fs = require('fs');
const path = require('path');

// Get report file from command line argument
const reportFile = process.argv[2];

if (!reportFile) {
    console.error('Error: Please provide a report file as an argument');
    console.error('Usage: node Bob/fix_advjs_from_report.js <report_file.txt>');
    console.error('Example: node Bob/fix_advjs_from_report.js Bob/bob_output/missing_advjs_imports_b_files.txt');
    process.exit(1);
}

// Check if report file exists
if (!fs.existsSync(reportFile)) {
    console.error(`Error: Report file not found: ${reportFile}`);
    process.exit(1);
}

console.log(`Reading report file: ${reportFile}\n`);

// Read and parse the report file
const reportContent = fs.readFileSync(reportFile, 'utf8');
const lines = reportContent.split('\n');

// Extract files from "Files MISSING these statements" section
const missingFiles = [];
let inMissingSection = false;

for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    
    if (line.includes('Files MISSING these statements')) {
        inMissingSection = true;
        continue;
    }
    
    if (inMissingSection && line.includes('Files that HAVE all required statements')) {
        break;
    }
    
    if (inMissingSection && line.match(/^\d+\.\s+(.+\.mdx)$/)) {
        const match = line.match(/^\d+\.\s+(.+\.mdx)$/);
        if (match) {
            missingFiles.push(match[1]);
        }
    }
}

if (missingFiles.length === 0) {
    console.log('No files need to be fixed! All files already have the required statements.');
    process.exit(0);
}

console.log(`Found ${missingFiles.length} files to fix:\n`);
missingFiles.forEach((file, index) => {
    console.log(`  ${index + 1}. ${file}`);
});
console.log('');

const reviewDir = path.join(__dirname, '..', 'src', 'pages', 'review');

let successCount = 0;
let errorCount = 0;
const errors = [];

// Process each file
missingFiles.forEach(filename => {
    const filePath = path.join(reviewDir, filename);
    
    if (!fs.existsSync(filePath)) {
        console.error(`✗ Error: File not found: ${filename}`);
        errorCount++;
        errors.push({ file: filename, error: 'File not found' });
        return;
    }
    
    try {
        let content = fs.readFileSync(filePath, 'utf8');
        let modified = false;
        
        // Step 1: Add imports after SliderJS4
        const lines = content.split('\n');
        const newLines = [];
        
        for (let i = 0; i < lines.length; i++) {
            newLines.push(lines[i]);
            
            // Check if this line contains SliderJS4 import
            if (lines[i].includes('import SliderJS4 from')) {
                // Check if next lines already have AdvJS imports
                const nextFewLines = lines.slice(i + 1, i + 4).join('\n');
                if (!nextFewLines.includes('import AdvJS2') && !nextFewLines.includes('import AdvJS3')) {
                    // Add the imports
                    newLines.push('import AdvJS2 from "../review/adv2";');
                    newLines.push('import AdvJS3 from "../review/adv3";');
                    modified = true;
                }
            }
        }
        
        content = newLines.join('\n');
        
        // Step 2: Add <AdvJS2/> after the last Button
        if (!content.includes('<AdvJS2/>') && !content.includes('<AdvJS2 />')) {
            // Find the last </Button> followed by optional whitespace and </div>
            const buttonPattern = /(<Button[^>]*>[\s\S]*?<\/Button>\s*)\n(\s*)<\/div>/g;
            let lastMatch = null;
            let match;
            
            while ((match = buttonPattern.exec(content)) !== null) {
                lastMatch = match;
            }
            
            if (lastMatch) {
                const replacement = lastMatch[1] + '\n' + lastMatch[2] + '<AdvJS2/>\n' + lastMatch[2] + '</div>';
                content = content.substring(0, lastMatch.index) + replacement + content.substring(lastMatch.index + lastMatch[0].length);
                modified = true;
            }
        }
        
        // Step 3: Add <AdvJS3/> at the end
        if (!content.includes('<AdvJS3/>') && !content.includes('<AdvJS3 />')) {
            if (!content.endsWith('\n')) {
                content += '\n';
            }
            content += '\n<AdvJS3 />\n';
            modified = true;
        }
        
        if (modified) {
            fs.writeFileSync(filePath, content, 'utf8');
            console.log(`✓ Fixed: ${filename}`);
            successCount++;
        } else {
            console.log(`- Skipped: ${filename} (already has all statements)`);
        }
        
    } catch (error) {
        console.error(`✗ Error processing ${filename}: ${error.message}`);
        errorCount++;
        errors.push({ file: filename, error: error.message });
    }
});

console.log('\n' + '='.repeat(60));
console.log('Summary:');
console.log(`Successfully fixed: ${successCount} files`);
console.log(`Errors: ${errorCount} files`);

if (errors.length > 0) {
    console.log('\nErrors:');
    errors.forEach(({ file, error }) => {
        console.log(`  - ${file}: ${error}`);
    });
    process.exit(1);
} else {
    console.log('\n✓ All files have been successfully updated!');
    console.log('\nYou can verify the changes by running:');
    const letter = path.basename(reportFile).match(/missing_advjs_imports_([a-z])_files\.txt/);
    if (letter) {
        console.log(`  node Bob/check_missing_advjs_imports.js ${letter[1]}`);
    }
}

// Made with Bob
